idle_bg = "#282828"
idle_fg = "#ebdbb2"
info_bg = "#282828"
info_fg = "#ebdbb2"
good_bg = "#282828"
good_fg = "#ebdbb2"
warning_bg = "#282828"
warning_fg = "#ebdbb2"
critical_bg = "#282828"
critical_fg = "#ebdbb2"
separator = "|"
separator_bg = "#282828"
separator_fg = "#7c6f64"
