[theme]
name = "gruvbox-custom.toml"

[icons]
name = "awesome6"

[[block]]
block = "sound"
show_volume_when_muted = true

[[block]]
block = "net"
format = "{ssid}"
interval = 5

[[block]]
block = "time"
interval = 5
format = "%m/%d %a %R"

[[block]]
block = "battery"
format = "{percentage}"
full_format = "{percentage}"
