[theme]
name = "gruvbox-dark"
[theme.overrides]
separator = "|"
separator_fg = "#7c6f64"
good_bg = "#282828"

[icons]
name = "awesome6"

[[block]]
block = "sound"

[[block]]
block = "net"
format = "{ssid}"
interval = 5

[[block]]
block = "time"
interval = 5
format = "%m/%d %R"

[[block]]
block = "battery"
format = "{percentage}"
full_format = "{percentage}"
