[theme]
theme = "gruvbox-custom.toml"

[icons]
icons = "awesome6"

[[block]]
block = "sound"
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
format = "$icon $ssid"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R') "
# interval = 5
# format = "%Y-%m-%d %a %R"

[[block]]
block = "battery"
format = " $icon $percentage "
full_format = " $icon $percentage "
charging_format = " $icon $percentage "
empty_format = " $icon $percentage "
not_charging_format = " $icon $percentage "
